# Generated by Django 6.0 on 2025-12-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Error Code', 'Error Code'), ('Component IO Check', 'Component IO Check'), ('Video Tutorial', 'Video Tutorial')], max_length=50, verbose_name='模式')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '查询日志',
                'verbose_name_plural': '查询日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频上传记录',
                'verbose_name_plural': '视频上传记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
